- hosts: localhost
  become: true
  tasks:
    - name: Check for vscode repo
      stat: path=/etc/yum.repos.d/vscode.repo
      register: fedora_vscode_installed

    - name: Import Microsoft GPG key
      rpm_key:
        state: present
        key: https://packages.microsoft.com/keys/microsoft.asc

    - name: Enable vscode repo
      yum_repository:
        name: code
        description: Visual Studio Code
        file: vscode
        baseurl: 'https://packages.microsoft.com/yumrepos/vscode'
        gpgkey: 'https://packages.microsoft.com/keys/microsoft.asc'
        gpgcheck: yes
        
    - name: Install VS Code
      dnf:
        name: code
        state: present

    - name: Enable Teams repo
      yum_repository:
        name: ms-teams
        description: Teams
        file: ms-teams
        baseurl: 'https://packages.microsoft.com/yumrepos/ms-teams'
        gpgkey: 'https://packages.microsoft.com/keys/microsoft.asc'
        gpgcheck: yes
        
    - name: Install Teams
      dnf:
        name: teams
        state: present
    - name: Enable brave repo
      yum_repository:
        name: brave
        description: Brave browser
        baseurl: 'https://brave-browser-rpm-release.s3.brave.com/x86_64/'
        gpgkey: 'https://brave-browser-rpm-release.s3.brave.com/brave-core.asc'
        gpgcheck: yes
    - name: Install Brave browser
      dnf:
        name: brave-browser
        state: present
    - name: Import Virtualbox GPG key
      rpm_key:
        state: present
        key: https://www.virtualbox.org/download/oracle_vbox.asc
    - name: Add Virtualbox repo
      shell:  'dnf config-manager \
        --add-repo \
          https://download.virtualbox.org/virtualbox/rpm/fedora/virtualbox.repo'
    - name: Install Virtualbox
      dnf:
        name: VirtualBox-6.1
        state: present
    - name: Install otro software adicional
      dnf:
        name: '{{ item }}'
        state: present
        update_cache: True
      with_items:
        - gimp
        - kdenlive       