- hosts: localhost
  become: true
  tasks:
    - name: Include vars of stuff.yaml into the 'stuff' variable (2.2).
      include_vars:
        file: ../vars/application-versions.yaml
    - name: Import RPM Fusion GPG keys
      become: yes
      rpm_key:
        state: present
        key: "https://rpmfusion.org/keys?action=AttachFile&do=get&target={{ item }}"
      with_items:
        - RPM-GPG-KEY-rpmfusion-free-fedora-{{ fedora_current }}
        - RPM-GPG-KEY-rpmfusion-nonfree-fedora-{{ fedora_current }}
    - name: install the rpmfusion repo packages
      become: yes
      dnf:
        name: "{{ item }}"
        state: present
      with_items:
        - http://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ fedora_current }}.noarch.rpm
        - http://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ fedora_current }}.noarch.rpm
    - name: Install basic packages
      dnf:
        name: "{{ item }}"
        state: present
        update_cache: True
        allowerasing: yes
      with_items:
        - openssh
        - zsh
        - curl
        - git
        - net-tools
        - google-roboto-*
        - "mozilla-fira*"
        - adobe-source-code-pro-fonts
        - fontconfig
        - htop
        - tuned
        - gstreamer1-plugin-openh264
        - mozilla-openh264
        - openh264
        - webp-pixbuf-loader
        - wl-clipboard
        - tilix
        - vlc
        - keepassxc
        - youtube-dl
        - neovim
        - ncdu
        - transmission
        - unar
        - unrar
        - gparted
        - filezilla
        - firewall-config
        - policycoreutils-gui
        - dkms
        - git-lfs
        - ffmpeg-libs
        - libva
        - libva-utils
        - tlp
        - cabextract
        - xorg-x11-font-utils
    - name: Install Oh My Zsh
      become: true
      become_user: "{{ usuario_sistema }}"
      shell: 'sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"'
      args:
        creates: "~/.oh-my-zsh"
    - name: Change shell for user to zsh
      become: true
      user:
        name: "{{ usuario_sistema }}"
        shell: /bin/zsh

    - name: Install zsh-autosuggestions plugin
      become: true
      become_user: "{{ usuario_sistema }}"
      ansible.builtin.git:
        repo: "https://github.com/zsh-users/zsh-autosuggestions"
        dest: "~/.oh-my-zsh/custom/plugins/zsh-autosuggestions"
        version: master
        force: yes
    - name: Install zsh-syntax-highlighting plugin
      become: true
      become_user: "{{ usuario_sistema }}"
      ansible.builtin.git:
        repo: "https://github.com/zsh-users/zsh-syntax-highlighting.git"
        dest: "~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting"
        version: master
        force: yes
    - name: Enable Oh My Zsh plugins
      become: true
      become_user: "{{ usuario_sistema }}"
      ansible.builtin.lineinfile:
        path: "~/.zshrc"
        regexp: '^plugins=\('
        line: "plugins=(git zsh-autosuggestions docker docker-compose kubectl kube-ps1 mvn gradle ufw zsh-syntax-highlighting helm dnf gh httpie ng npm node nvm gitignore)"
        backup: yes
