- hosts: localhost
  become: true
  tasks:
    - name: Check for vscode repo
      stat: path=/etc/yum.repos.d/vscode.repo
      register: fedora_vscode_installed

    - name: Import Microsoft GPG key
      rpm_key:
        state: present
        key: https://packages.microsoft.com/keys/microsoft.asc

    - name: Enable vscode repo
      yum_repository:
        name: code
        description: Visual Studio Code
        file: vscode
        baseurl: "https://packages.microsoft.com/yumrepos/vscode"
        gpgkey: "https://packages.microsoft.com/keys/microsoft.asc"
        gpgcheck: yes

    - name: Install extra packages
      dnf:
        name: "{{ item }}"
        state: present
        update_cache: True
      with_items:
        - solaar
        - pass

    - name: Enable brave repo
      yum_repository:
        name: brave
        description: Brave browser
        baseurl: "https://brave-browser-rpm-release.s3.brave.com/x86_64/"
        gpgkey: "https://brave-browser-rpm-release.s3.brave.com/brave-core.asc"
        gpgcheck: yes

