- hosts: localhost
  become: true
  tasks:
    - name: Include vars of stuff.yaml into the 'stuff' variable (2.2).
      include_vars:
        file: ../vars/application-versions.yaml
    - name: Install developer packages
      dnf:
        name: "{{ item }}"
        state: present
        update_cache: True
      with_items:
        - helm
        - awscli
        - httpie
        - openjfx
    - name: Add Kubernetes repository for kubectl
      yum_repository:
        name: kubernetes
        description: Kubernetes
        baseurl: https://pkgs.k8s.io/core:/stable:/v1.29/rpm/
        gpgkey: https://pkgs.k8s.io/core:/stable:/v1.29/rpm/repodata/repomd.xml.key
        gpgcheck: yes
        enabled: yes
    - name: Install kubectl
      dnf:
        name: kubectl
        state: present
    - name: "Remove manually installed minikube binary if it exists"
      ansible.builtin.file:
        path: /usr/local/bin/minikube
        state: absent # Clean up old binary-based installation
    - name: "Install minikube from the latest official RPM"
      ansible.builtin.dnf:
        name: "https://storage.googleapis.com/minikube/releases/latest/minikube-latest.x86_64.rpm"
        state: present
        disable_gpg_check: true # The RPM is not signed
    - name: Install nvm
      become: true
      become_user: "{{ usuario_sistema }}"
      shell: "curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash"
      args:
        creates: "~/.nvm/nvm.sh"
    - name: Install latest LTS version of node
      become: true
      become_user: "{{ usuario_sistema }}"
      shell: "source ~/.nvm/nvm.sh && nvm install --lts"
      args:
        creates: "~/.nvm/versions/node"

    - name: Install sdkman
      become: true
      become_user: "{{ usuario_sistema }}"
      shell: 'curl -s "https://get.sdkman.io" | bash'
      args:
        creates: "~/.sdkman/bin/sdkman-init.sh"

    - name: Install latest Java with sdkman
      become: true
      become_user: "{{ usuario_sistema }}"
      shell: "source ~/.sdkman/bin/sdkman-init.sh && sdk install java"
      args:
        creates: "~/.sdkman/candidates/java/current"

    - name: Install latest Maven with sdkman
      become: true
      become_user: "{{ usuario_sistema }}"
      shell: "source ~/.sdkman/bin/sdkman-init.sh && sdk install maven"
      args:
        creates: "~/.sdkman/candidates/maven/current"

    - name: Install latest Gradle with sdkman
      become: true
      become_user: "{{ usuario_sistema }}"
      shell: "source ~/.sdkman/bin/sdkman-init.sh && sdk install gradle"
      args:
        creates: "~/.sdkman/candidates/gradle/current"

    - name: Remove old GitHub CLI repository file if it exists
      ansible.builtin.file:
        path: /etc/yum.repos.d/github-cli.repo
        state: absent

    - name: Add GitHub CLI repository
      ansible.builtin.yum_repository:
        name: "gh-cli"
        description: "GitHub CLI"
        baseurl: "https://cli.github.com/packages/rpm"
        gpgkey: "https://keys.openpgp.org/vks/v1/by-fingerprint/0A9623335A7542187235564B528995BF449F85C3"
        gpgcheck: yes

    - name: Install GitHub CLI
      ansible.builtin.dnf:
        name: gh
