# https://www.debugpoint.com/2021/04/gnome-40-extensions/
- hosts: localhost
  become: true
  tasks:
    - name: Include vars of stuff.yaml into the 'stuff' variable (2.2).
      include_vars:
        file: ../vars/application-versions.yaml
    - name: Install gnome packages
      dnf:
        name: "{{ item }}"
        state: present
        update_cache: True
      with_items:
        - alacarte
        - file-roller
        - gnome-tweak-tool
        - gnome-extensions-app
        - uget
        - adwaita-gtk2-theme
    - name: Install psutil for dconf module
      dnf:
        name: python3-psutil
        state: present
    - name: Install Microsoft Core Fonts
      dnf:
        name: https://downloads.sourceforge.net/project/mscorefonts2/rpms/msttcore-fonts-installer-2.6-1.noarch.rpm
        state: present
        disable_gpg_check: True
    - name: Set dark theme for GTK applications
      become: true
      become_user: "{{ usuario_sistema }}"
      community.general.dconf:
        key: "/org/gnome/desktop/interface/gtk-theme"
        value: "'Adwaita-dark'"
    - name: Set dark theme for legacy (GTK2) applications
      become: true
      become_user: "{{ usuario_sistema }}"
      community.general.dconf:
        key: "/org/gnome/settings-daemon/plugins/xsettings/overrides"
        value: "{'Gtk/ThemeName': <'Adwaita-dark'>}"
    - name: Set color scheme to prefer-dark for modern applications
      become: true
      become_user: "{{ usuario_sistema }}"
      community.general.dconf:
        key: "/org/gnome/desktop/interface/color-scheme"
        value: "'prefer-dark'"
