
- hosts: localhost
  become: true
  tasks:
    - name: Include vars of stuff.yaml into the 'stuff' variable (2.2).
      include_vars:
        file: ../vars/application-versions.yaml  
    - name: Configura Fracctional Scaling en X11 1
      template:
        src: ../templates/hidpi-desktop.j2
        dest: "/usr/share/gdm/greeter/autostart/hidpi.desktop"    
        owner: root
        group: root 
    - name: Configura Fracctional Scaling en X11 2
      template:
        src: ../templates/hidpi-desktop.j2
        dest: "/etc/xdg/autostart/hidpi.desktop"         
        owner: root
        group: root 
    - name: Configura Fracctional Scaling en X11 3
      template:
        src: ../templates/hidpi.j2
        dest: "/usr/local/bin/hidpi.sh"   
        owner: root
        group: root
        mode: u=rwx,g=rx,o=rx
    - name: Configura Variables de Fracctional Scaling en X11
      template:
        src: ../templates/hidpi-env-vars.j2
        dest: "/etc/profile.d/hidpi-env-vars.sh"
        owner: root
        group: root
        mode: u=rwx,g=rx,o=rx