---
- name: Install Ollama
  hosts: localhost
  become: true
  tasks:
    - name: Install Ollama
      become: true
      shell: "curl -fsSL https://ollama.com/install.sh | sh"
      args:
        creates: "/usr/local/bin/ollama"
